name: Build

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install dependencies 📦
        run: pnpm install

      - name: Execute unit tests 🧪
        run: npm run test:unit:coverage

      - name: Upload test coverage 🧪
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/clover.xml,./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - name: Build App
        run: npm run build
